name = "MaxwellGuide"
uuid = "1a361701-5cf3-415b-af48-956f67dbd5f6"
license = "MIT"
desc = "High-performance finite-difference frequency-domain (FDFD) solver of electromagnetic waveguide mode equations written in Julia"
authors = ["Wonseok Shin <wsshin97@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbbreviatedTypes = "1766def0-c946-4dda-a59e-d0d07f8410f7"
MaxwellBase = "7ddc1c72-b467-4b56-ac1e-188734e3cfa7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "^1.5"
AbbreviatedTypes = "^0.1.0"
MaxwellBase = "^0.1.0"
Reexport = "^1.0.0"

[extras]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Statistics", "Test"]
